//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSMarkRedux.locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class locale_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSMarkRedux.locales.locale_EN", typeof(locale_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _CommunityEdition.
        /// </summary>
        internal static string _Edition {
            get {
                return ResourceManager.GetString("_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Architecture:.
        /// </summary>
        internal static string archID {
            get {
                return ResourceManager.GetString("archID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoUpdaterNetStandard Version:.
        /// </summary>
        internal static string autoUpdaterNetStandardVersion {
            get {
                return ResourceManager.GetString("autoUpdaterNetStandardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the amount of calculations you&apos;d like to be performed in millions:.
        /// </summary>
        internal static string calculations {
            get {
                return ResourceManager.GetString("calculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set the custom amount of calculations..
        /// </summary>
        internal static string calculations_Failed {
            get {
                return ResourceManager.GetString("calculations_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update for CSMark is available!.
        /// </summary>
        internal static string checkForUpdate_Available {
            get {
                return ResourceManager.GetString("checkForUpdate_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changelog for the latest version can be found here:.
        /// </summary>
        internal static string checkForUpdate_ChangeLog {
            get {
                return ResourceManager.GetString("checkForUpdate_ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To download the update, go to this URL:.
        /// </summary>
        internal static string checkForUpdate_DownloadInstruction {
            get {
                return ResourceManager.GetString("checkForUpdate_DownloadInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates failed. Proceeding to start CSMark..
        /// </summary>
        internal static string checkForUpdate_Failed {
            get {
                return ResourceManager.GetString("checkForUpdate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed CSMark Version:.
        /// </summary>
        internal static string checkForUpdate_Installed {
            get {
                return ResourceManager.GetString("checkForUpdate_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest CSMark Version:.
        /// </summary>
        internal static string checkForUpdate_Latest {
            get {
                return ResourceManager.GetString("checkForUpdate_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experienced networking issues whilst checking for updates..
        /// </summary>
        internal static string checkForUpdate_NetworkIssues {
            get {
                return ResourceManager.GetString("checkForUpdate_NetworkIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates to CSMark. This should just take a moment..
        /// </summary>
        internal static string checkForUpdate_Notice {
            get {
                return ResourceManager.GetString("checkForUpdate_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds to check for updates..
        /// </summary>
        internal static string checkForUpdate_Time {
            get {
                return ResourceManager.GetString("checkForUpdate_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Took.
        /// </summary>
        internal static string checkForUpdate_Took {
            get {
                return ResourceManager.GetString("checkForUpdate_Took", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is up to date..
        /// </summary>
        internal static string checkForUpdate_UpToDate {
            get {
                return ResourceManager.GetString("checkForUpdate_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To run the test with a specific amount of calculations, please enter.
        /// </summary>
        internal static string command_CustomCalc {
            get {
                return ResourceManager.GetString("command_CustomCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give feedback, or report bugs by opening a GitHub issue at https://github.com/CSMarkBenchmark/CSMark/issues/new.
        /// </summary>
        internal static string command_Feedback {
            get {
                return ResourceManager.GetString("command_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To force results to be saved immediately after running the benchmark, enter the benchmark command followed by.
        /// </summary>
        internal static string command_ForceSave {
            get {
                return ResourceManager.GetString("command_ForceSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string command_Number0 {
            get {
                return ResourceManager.GetString("command_Number0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string command_Number1 {
            get {
                return ResourceManager.GetString("command_Number1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string command_Number2 {
            get {
                return ResourceManager.GetString("command_Number2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string command_Number3 {
            get {
                return ResourceManager.GetString("command_Number3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To run the multi threaded tests only, please enter.
        /// </summary>
        internal static string command_runMulti {
            get {
                return ResourceManager.GetString("command_runMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To run the single threaded and multi threaded tests, please enter.
        /// </summary>
        internal static string command_runNormal {
            get {
                return ResourceManager.GetString("command_runNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To run the single threaded tests only, please enter.
        /// </summary>
        internal static string command_runSingle {
            get {
                return ResourceManager.GetString("command_runSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To run the stress test utility, please enter.
        /// </summary>
        internal static string command_runStress {
            get {
                return ResourceManager.GetString("command_runStress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To run test using a specified amount of threads enter the benchmark command followed by.
        /// </summary>
        internal static string command_runThreads {
            get {
                return ResourceManager.GetString("command_runThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _save.
        /// </summary>
        internal static string command_Save {
            get {
                return ResourceManager.GetString("command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _threads.
        /// </summary>
        internal static string command_Threads {
            get {
                return ResourceManager.GetString("command_Threads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string commandAbout {
            get {
                return ResourceManager.GetString("commandAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _calc.
        /// </summary>
        internal static string commandCalc {
            get {
                return ResourceManager.GetString("commandCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string commandClear {
            get {
                return ResourceManager.GetString("commandClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string commandExit {
            get {
                return ResourceManager.GetString("commandExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string commandHelp {
            get {
                return ResourceManager.GetString("commandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not a command supported by CSMark! Please enter a supported command..
        /// </summary>
        internal static string commandNotSupported {
            get {
                return ResourceManager.GetString("commandNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of supported commands:.
        /// </summary>
        internal static string commands_SupportedInfo {
            get {
                return ResourceManager.GetString("commands_SupportedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information on what these commands do, please go to:.
        /// </summary>
        internal static string commandsExtraInfo {
            get {
                return ResourceManager.GetString("commandsExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/CSMarkBenchmark/CSMark/blob/master/docs/Commands.md.
        /// </summary>
        internal static string commandsExtraInfo_URL {
            get {
                return ResourceManager.GetString("commandsExtraInfo_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERSION.
        /// </summary>
        internal static string commandVersion {
            get {
                return ResourceManager.GetString("commandVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the results to a Text File?.
        /// </summary>
        internal static string confirmSave {
            get {
                return ResourceManager.GetString("confirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSMarkLib Version:.
        /// </summary>
        internal static string csmarkLibVersion {
            get {
                return ResourceManager.GetString("csmarkLibVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSMark RunTime Identifier:.
        /// </summary>
        internal static string csmarkRID {
            get {
                return ResourceManager.GetString("csmarkRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSMark Version:.
        /// </summary>
        internal static string csmarkVersion {
            get {
                return ResourceManager.GetString("csmarkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2017 AluminiumTech
        ///This product is licensed under the GNU General Public License (GPL) v3 open source license.
        ///
        ///This is free software (As defined at https://www.gnu.org/philosophy/free-sw.html) :
        ///you can re-distribute it and/or modify it under the terms of the GNU General Public License as published by
        ///the Free Software Foundation.
        ///
        ///This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY;
        ///without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PART [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS ID:.
        /// </summary>
        internal static string osID {
            get {
                return ResourceManager.GetString("osID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string respondHours {
            get {
                return ResourceManager.GetString("respondHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string respondMinutes {
            get {
                return ResourceManager.GetString("respondMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string respondSeconds {
            get {
                return ResourceManager.GetString("respondSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM.
        /// </summary>
        internal static string respondSystem {
            get {
                return ResourceManager.GetString("respondSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string responseNo {
            get {
                return ResourceManager.GetString("responseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string responseYes {
            get {
                return ResourceManager.GetString("responseYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter YES or NO.
        /// </summary>
        internal static string responseYorN {
            get {
                return ResourceManager.GetString("responseYorN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text file could not be saved..
        /// </summary>
        internal static string save_Fail {
            get {
                return ResourceManager.GetString("save_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you installed CSMark using the .exe installer, please run CSMark as an administrator to be able to save the results file..
        /// </summary>
        internal static string save_ReminderInstall {
            get {
                return ResourceManager.GetString("save_ReminderInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the time format in SECONDS, MINUTES or HOURS..
        /// </summary>
        internal static string selectTimeFormat {
            get {
                return ResourceManager.GetString("selectTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting CSMark..
        /// </summary>
        internal static string starting {
            get {
                return ResourceManager.GetString("starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BREAK.
        /// </summary>
        internal static string stressTest_Break {
            get {
                return ResourceManager.GetString("stressTest_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting stress test..
        /// </summary>
        internal static string stressTest_Start {
            get {
                return ResourceManager.GetString("stressTest_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string stressTest_Stop {
            get {
                return ResourceManager.GetString("stressTest_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To stop the stress test, please exit the program or enter STOP or BREAK.
        /// </summary>
        internal static string stressTest_StopMessage {
            get {
                return ResourceManager.GetString("stressTest_StopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to run the stress test for.
        /// </summary>
        internal static string stressTestConfirm {
            get {
                return ResourceManager.GetString("stressTestConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Tests....
        /// </summary>
        internal static string test_Starting {
            get {
                return ResourceManager.GetString("test_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like to run all from 1 to the total amount on your CPU.please enter SYSTEM..
        /// </summary>
        internal static string threads_All {
            get {
                return ResourceManager.GetString("threads_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many threads would you like to complete the benchmark?.
        /// </summary>
        internal static string threads_HowMany {
            get {
                return ResourceManager.GetString("threads_HowMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to run a timed Stress Test?.
        /// </summary>
        internal static string timedStressTest {
            get {
                return ResourceManager.GetString("timedStressTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many.
        /// </summary>
        internal static string timeFormat_HowMany {
            get {
                return ResourceManager.GetString("timeFormat_HowMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to would you like the stress test to run for?.
        /// </summary>
        internal static string timeFormat_Time {
            get {
                return ResourceManager.GetString("timeFormat_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Edition.
        /// </summary>
        internal static string title_CommunityEdition {
            get {
                return ResourceManager.GetString("title_CommunityEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSMark.
        /// </summary>
        internal static string title_Name {
            get {
                return ResourceManager.GetString("title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Support Status, go to https://github.com/CSMarkBenchmark/CSMark/blob/master/Support.md.
        /// </summary>
        internal static string title_Support {
            get {
                return ResourceManager.GetString("title_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to CSMark Community Edition..
        /// </summary>
        internal static string title_Welcome {
            get {
                return ResourceManager.GetString("title_Welcome", resourceCulture);
            }
        }
    }
}
